Added ducks.party instance, set hostname for redis container
syeopite/priviblur pull request #36
Opened 2024-04-21 16:40 UTC by nyuuzyou

2024-05-03 21:24 UTC, TheFrenchGhosty requested changes

2024-05-03 21:24 UTC, TheFrenchGhosty commented on docker-compose.yml
> +    hostname: redis
Don't do that.

2024-05-03 21:24 UTC, TheFrenchGhosty commented on config.example.toml
> +    # url = "redis://redis:6379"
```suggestion
    # url = "redis://priviblur-redis:6379"
```

2024-05-04 01:07 UTC, syeopite requested changes
Can you remove the docker and config changes? I'll be merging this alongside #37 which implements the changes here and then some.

2024-05-07 07:25 UTC, merged

2024-06-30 21:25 UTC, syeopite commented
@nyuuzyou Your instance is more than a month out of date! Please update it or I'll have to remove it from the instance list.